log:
  level: "debug"
ssh:
  listen: 0.0.0.0:8222
  hostkeys:
  - example/ssh_host_rsa_key
  - example/ssh_host_ed25519_key
auth:
  url: "https://localhost:8081"
  cacert: authServer/example/server/ca.crt
  cert: authServer/example/clientCert1/client.crt
  key: authServer/example/clientCert1/client.key
  pubkey: true
  password: true
configserver:
  url: https://localhost:8080/config
  cacert: configServer/example/server/ca.crt
  cert: configServer/example/clientCert1/client.crt
  key: configServer/example/clientCert1/client.key
