#!/bin/bash
set -e
. ./helper-scripts/docker-env-defaults.sh
. ./helper-scripts/docker-debug-ssh.sh
if [ "$DEBUG_SSH" == "true" ]; then
  mkdir -p ~/.ssh
  ssh-keyscan github.com >> ~/.ssh/known_hosts
  tmux new-session -d -s build ./helper-scripts/docker-build-all.sh
else
./helper-scripts/docker-build-all.sh
fi
exit 0
