#!/bin/bash
. ./helper-scripts/docker-env-defaults.sh
. ./helper-scripts/docker-debug-ssh.sh
if [ "$DEBUG_SSH" == "true" ]; then
  tmux new-session -d -s push ./helper-scripts/docker-push-all.sh
else
  ./helper-scripts/docker-push-all.sh
fi
