#!/bin/bash
set -e
. ./helper-scripts/docker-env-defaults.sh
. ./helper-scripts/docker-debug-ssh.sh
if [ "$DEBUG_SSH" == "true" ]; then
  tmux new-session -d -s test ./helper-scripts/docker-test-all.sh
else
  ./helper-scripts/docker-test-all.sh
fi
exit 0
