---
users: # map with users
  user1: # username
    password: ee26b0dd4af7e749aa1a8ee3c10ae9923f618980772e473f8819a5d4940e0db27ac185f8a0e1d5f84f88bc887fd67b143732c304cc5fa9ad8e6f57f50028a8ff # password sha512 
    ips: # allowed cidrs
    - 1.1.1.1/32
    - 10.5.0.0/16
server: # server config
  listen: ":8080"  # default :8080 at http or 8443 on https 
  tls: # enable tls
    cert: example/server/server_cert.pem # cert
    key: example/server/server_key.pem # key
  auth: # aatuh for server
    credentials: # basic auth
      test: ee26b0dd4af7e749aa1a8ee3c10ae9923f618980772e473f8819a5d4940e0db27ac185f8a0e1d5f84f88bc887fd67b143732c304cc5fa9ad8e6f57f50028a8ff # username: password sha512
    mtls: # enable clienttls (mtls)
    - ca: example/clientCert1/ca.crt # trusted ca 1
    - ca: example/clientCert2/ca.crt # trusted ca 2
